version: "3"
services:

  zbx-agent:
    tty: true
    image: zabbix/zabbix-agent:centos-3.4-latest
    container_name: zbx-agent
    hostname: zbx-agent
#    environment:
#      DB_SERVER_HOST:       mysql-zbx
#      MYSQL_DATABASE:       ${DB_NAME}
#      MYSQL_USER:           ${DB_USER}
#      MYSQL_PASSWORD:       ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
#      ZBX_JAVAGATEWAY:      java-gateway-zbx
#      ZBX_DEBUGLEVEL:       ${LOG_LEVEL}
#    volumes:
#      - ./env/var/lib/mysql:/var/lib/mysql:rw
    ports:
      - "10050:10050"
